name: flutter_app_testing
description: A Flutter app for image classification

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  image_picker: ^0.8.4+4
  file_picker: ^5.3.2
  geolocator: ^8.0.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  google_maps_flutter: ^2.3.1
  permission_handler: ^10.3.0
  camera: ^0.10.5+2
  webview_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: marcellus
      fonts:
        - asset: images/Marcellus-Regular.ttf
  assets:
    - images/mapLogo.png
    - images/infoLogo.png
    - images/background.png
    - images/cameraNew.png
    - images/backgroundnew.png
    - images/.